import { useMemo } from "react";
import { useTranslation } from "react-i18next";

export function useAppText() {
  const { t } = useTranslation();
  return useMemo(() => ({
    title: t("deck.title"),
    signedInAs: t("deck.signedInAs"),
    usingSession: t("deck.usingSession"),
    realtimeOff: t("deck.realtimeOff"),
    settingsHint: t("deck.settingsHint"),
    settingsButton: t("deck.settingsButton"),
    connectionLog: t("deck.connectionLog"),
    recentLabel: t("deck.recentLabel"),
    addLabel: t("deck.addLabel"),
    addMentions: t("deck.addMentions"),
    addChannelWatch: t("deck.addChannelWatch"),
    addDmWatch: t("deck.addDmWatch"),
    addSearch: t("deck.addSearch"),
    addSaved: t("deck.addSaved"),
    addDiagnostics: t("deck.addDiagnostics"),
    viewsLabel: t("deck.viewsLabel"),
    savedSetsLabel: t("deck.savedSetsLabel"),
    menuLabel: t("deck.menuLabel"),
    layoutLabel: t("deck.layoutLabel"),
    reorderPanes: t("deck.reorderPanes"),
    applyOrder: t("deck.applyOrder"),
    cancel: t("deck.cancel"),
    saveCurrentSet: t("deck.saveCurrentSet"),
    savedColumns: (count: number) => t("deck.savedColumns", { count }),
    exportLayout: t("deck.exportLayout"),
    importLayout: t("deck.importLayout"),
    choosePane: t("deck.choosePane"),
    loading: t("deck.loading"),
    sessionExpired: t("deck.sessionExpired"),
    apiSessionExpired: t("deck.apiSessionExpired"),
    apiPermissionDenied: t("deck.apiPermissionDenied"),
    apiRateLimited: t("deck.apiRateLimited"),
    apiServerUnavailable: t("deck.apiServerUnavailable"),
    apiRequestFailed: (status: number | string) => t("deck.apiRequestFailed", { status }),
    failedToLoad: t("deck.failedToLoad"),
    failedToLoadMentions: t("deck.failedToLoadMentions"),
    column: t("deck.column"),
    columns: t("deck.columns"),
    teamLabel: t("deck.teamLabel"),
    selectTeam: t("deck.selectTeam"),
    allTeams: t("deck.allTeams"),
    unreadOnly: t("deck.unreadOnly"),
    scope: t("deck.scope"),
    mentionBadge: (count: number, perTeam: boolean) =>
      t(perTeam ? "deck.mentionBadgePerTeam" : "deck.mentionBadgeAllTeams", { count }),
    noMentions: t("deck.noMentions"),
    noUnreadMentions: t("deck.noUnreadMentions"),
    mentionsWillAppear: t("deck.mentionsWillAppear"),
    unreadOnlyNote: t("deck.unreadOnlyNote"),
    unreadSeparatorLabel: t("deck.unreadSeparatorLabel"),
    markRead: t("deck.markRead"),
    jumpToLatest: t("deck.jumpToLatest"),
    newPosts: (count: number) => t("deck.newPosts", { count }),
    allTeamsNote: t("deck.allTeamsNote"),
    channelLabel: t("deck.channelLabel"),
    selectChannel: t("deck.selectChannel"),
    selectDm: t("deck.selectDm"),
    directMessage: t("deck.directMessage"),
    pinnedTarget: t("deck.pinnedTarget"),
    unknownTeam: t("deck.unknownTeam"),
    pickDmOrGroup: t("deck.pickDmOrGroup"),
    pickTeamAndChannel: t("deck.pickTeamAndChannel"),
    selectATeam: t("deck.selectATeam"),
    selectATeamDesc: t("deck.selectATeamDesc"),
    selectAChannel: t("deck.selectAChannel"),
    selectADm: t("deck.selectADm"),
    selectChannelDesc: t("deck.selectChannelDesc"),
    selectDmDesc: t("deck.selectDmDesc"),
    queryLabel: t("deck.queryLabel"),
    searchTerms: t("deck.searchTerms"),
    applySearch: t("deck.applySearch"),
    noRecentEvents: t("deck.noRecentEvents"),
    diagnosticsTitle: t("deck.diagnosticsTitle"),
    diagnosticsDesc: t("deck.diagnosticsDesc"),
    diagnosticsStatus: t("deck.diagnosticsStatus"),
    diagnosticsApiTps: t("deck.diagnosticsApiTps"),
    diagnosticsAvgLatency: t("deck.diagnosticsAvgLatency"),
    diagnosticsErrorRate: t("deck.diagnosticsErrorRate"),
    diagnosticsRecentSuffix: t("deck.diagnosticsRecentSuffix"),
    diagnosticsInFlight: t("deck.diagnosticsInFlight"),
    diagnosticsFailedSuffix: t("deck.diagnosticsFailedSuffix"),
    diagnosticsWsReconnects: t("deck.diagnosticsWsReconnects"),
    diagnosticsRender: t("deck.diagnosticsRender"),
    diagnosticsAverageShort: t("deck.diagnosticsAverageShort"),
    diagnosticsLastShort: t("deck.diagnosticsLastShort"),
    diagnosticsNotAvailable: t("deck.diagnosticsNotAvailable"),
    diagnosticsRecentSyncLog: t("deck.diagnosticsRecentSyncLog"),
    diagnosticsPerformanceHint: t("deck.diagnosticsPerformanceHint"),
    diagnosticsStatusHealthy: t("deck.diagnosticsStatusHealthy"),
    diagnosticsStatusDegraded: t("deck.diagnosticsStatusDegraded"),
    diagnosticsStatusError: t("deck.diagnosticsStatusError"),
    diagnosticsWsIdle: t("deck.diagnosticsWsIdle"),
    diagnosticsWsConnecting: t("deck.diagnosticsWsConnecting"),
    diagnosticsWsConnected: t("deck.diagnosticsWsConnected"),
    diagnosticsWsReconnecting: t("deck.diagnosticsWsReconnecting"),
    diagnosticsWsOffline: t("deck.diagnosticsWsOffline"),
    diagnosticsWsError: t("deck.diagnosticsWsError"),
    diagnosticsWsAuthFailed: t("deck.diagnosticsWsAuthFailed"),
    diagnosticsPolling: t("deck.diagnosticsPolling"),
    recommendedDiagnostics: t("deck.recommendedDiagnostics"),
    resizeLabel: t("deck.resizeLabel"),
    resizeDrag: t("deck.resizeDrag"),
    moreActionsLabel: t("deck.moreActionsLabel"),
    focusPane: t("deck.focusPane"),
    exitFocus: t("deck.exitFocus"),
    collapseControls: (name: string) => t("deck.collapseControls", { name }),
    expandControls: (name: string) => t("deck.expandControls", { name }),
    groupDirectMessage: t("deck.groupDirectMessage"),
    openInNewTab: t("deck.openInNewTab"),
    downloadImage: t("deck.downloadImage"),
    close: t("deck.close"),
    zoomOut: t("deck.zoomOut"),
    fitToScreen: t("deck.fitToScreen"),
    zoomIn: t("deck.zoomIn"),
    fillScreen: t("deck.fillScreen"),
    loadingMore: t("deck.loadingMore"),
    loadMore: t("deck.loadMore"),
    allPostsLoaded: t("deck.allPostsLoaded"),
    moveLeft: t("deck.moveLeft"),
    moveRight: t("deck.moveRight"),
    refresh: t("deck.refresh"),
    pausePolling: t("deck.pausePolling"),
    resumePolling: t("deck.resumePolling"),
    removeColumn: t("deck.removeColumn"),
    startWithChannel: t("deck.startWithChannel"),
    startWithChannelDesc: t("deck.startWithChannelDesc"),
    watchCurrentChannel: t("deck.watchCurrentChannel"),
    recommendedMentions: t("deck.recommendedMentions"),
    recommendedMentionsDesc: t("deck.recommendedMentionsDesc"),
    recommendedSaved: t("deck.recommendedSaved"),
    recommendedSavedDesc: t("deck.recommendedSavedDesc"),
    useCurrentChannel: t("deck.useCurrentChannel"),
    recommendedDiagnosticsDesc: t("deck.recommendedDiagnosticsDesc"),
    failedToLoadPosts: t("deck.failedToLoadPosts"),
    failedToLoadChannels: t("deck.failedToLoadChannels"),
    unknownError: t("deck.unknownError"),
    loadingDirectMessages: t("deck.loadingDirectMessages"),
    loadingChannelPosts: t("deck.loadingChannelPosts"),
    loadingDirectMessagesDesc: t("deck.loadingDirectMessagesDesc"),
    loadingChannelPostsDesc: t("deck.loadingChannelPostsDesc"),
    noPostsYet: t("deck.noPostsYet"),
    noDirectPosts: t("deck.noDirectPosts"),
    noChannelPosts: t("deck.noChannelPosts"),
    initialLoadingDesc: t("deck.initialLoadingDesc"),
    pickTeam: t("deck.pickTeam"),
    saveSearchQuery: t("deck.saveSearchQuery"),
    savedSearches: t("deck.savedSearches"),
    removeSavedSearch: (query: string) => t("deck.removeSavedSearch", { query }),
    searchSyntax: t("deck.searchSyntax"),
    searchSyntaxDesc: t("deck.searchSyntaxDesc"),
    setSearch: t("deck.setSearch"),
    setSearchDesc: t("deck.setSearchDesc"),
    failedToLoadResults: t("deck.failedToLoadResults"),
    loadingKeywordMatches: t("deck.loadingKeywordMatches"),
    loadingSearchResults: t("deck.loadingSearchResults"),
    loadingSearchDesc: t("deck.loadingSearchDesc"),
    noResults: t("deck.noResults"),
    noResultsDesc: t("deck.noResultsDesc"),
    flaggedPosts: t("deck.flaggedPosts"),
    failedToLoadSavedPosts: t("deck.failedToLoadSavedPosts"),
    loadingSavedPosts: t("deck.loadingSavedPosts"),
    loadingSavedPostsDesc: t("deck.loadingSavedPostsDesc"),
    noSavedPosts: t("deck.noSavedPosts"),
    noSavedPostsDesc: t("deck.noSavedPostsDesc"),
    viewNamePrompt: t("deck.viewNamePrompt"),
    hideDeck: t("deck.hideDeck"),
    showDeck: t("deck.showDeck"),
    moveViewUp: (name: string) => t("deck.moveViewUp", { name }),
    moveViewDown: (name: string) => t("deck.moveViewDown", { name }),
    closeView: (name: string) => t("deck.closeView", { name }),
    removeSavedView: (name: string) => t("deck.removeSavedView", { name }),
    sessionExpiredDesc: t("deck.sessionExpiredDesc"),
    reloadMattermost: t("deck.reloadMattermost"),
    pollingRealtimeAuthFailed: t("deck.pollingRealtimeAuthFailed"),
    realtime: t("deck.realtime"),
    polling: t("deck.polling"),
  }), [t]);
}
